In [2]:
import os
from glob import glob
import sys
import warnings
import pandas as pd

import time
import pyperclip as clip

pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:20,.2f}'.format

In [3]:
cd

/Users/karatechop

In [4]:
cd /Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022\ \(CSV\)

/Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022 (CSV)

## Combining all Formatted Sheets

In [5]:
import os
from glob import glob

PATH = os.getcwd()
EXT = "*.csv"

cols = ['date','time','sex','race','type','duration','city']
count = 0


for path, subdir, files in os.walk(PATH):
    for file in glob(os.path.join(path, EXT)):
        if 'ALL-' in file and 'AB953' in file:  
            if count == 0: 
                main = pd.read_csv(file, index_col = None)
                print(file)
                main['city'] = f'{file[-30:]}'.replace('.csv','').split("/")[1]
                main.columns = map(str.lower, main.columns)
                main = main.loc[:,cols]
                count+=1
                print(main.columns,main.shape,f'{file[-30:]} is starting main file\n',main['time'].value_counts()[:50],'\n\n')

            else:
                try: 
                    df = pd.read_csv(file, index_col=None)
                    df['city'] = f'{file[-30:]}'.replace('.csv','').split("/")[1]
                    df.columns = map(str.lower, df.columns)
                    df = df.loc[:,cols]
                    print(df.columns,df.shape,f'{file[-30:]} is starting main file\n',df['time'].value_counts()[:50],'\n\n')
                    main = pd.concat([main,df])
                    print(f'{file[-30:]} concatenated!')
                except:
                    print(f'{file} failed to merge')
                    pass
                
main = main[(main['city']!='working_main')]
print(f'final shape of main is {main.shape}')

/Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022 (CSV)/Wave 2/SJPD CAU (Crime Analysis Unit)/ALL-SJPD-AB953.csv
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (50443, 7) lysis Unit)/ALL-SJPD-AB953.csv is starting main file
 10:00    347
11:00    303
09:00    293
17:00    262
23:00    253
18:00    247
10:30    233
09:30    229
08:30    211
08:00    195
19:00    192
11:30    181
20:00    180
12:00    180
08:45    177
22:00    176
13:00    175
23:30    173
14:00    159
10:15    157
10:20    155
02:00    155
01:00    154
09:15    148
09:45    147
16:00    146
21:00    146
08:50    144
22:30    144
12:30    143
09:50    143
08:40    142
09:25    140
10:45    140
17:30    139
16:30    138
13:30    137
09:40    134
11:15    134
18:30    133
08:35    132
09:20    132
15:00    130
09:35    127
08:15    125
14:30    124
03:00    123
08:05    120
10:05    119
11:45    119
Name: time, dtype: int64


Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (36670, 7) Police Dept/ALL-LBPD-AB953.csv is starting main file
 17:30    91
08:30    89
10:00    87
11:00    85
10:30    82
09:30    81
09:00    74
18:00    73
08:00    73
16:20    72
16:00    72
17:40    71
10:50    70
17:00    70
15:30    70
18:30    70
19:30    69
13:00    69
16:30    68
15:00    68
14:00    68
13:30    67
08:20    66
17:20    63
12:15    62
17:50    62
08:10    62
08:50    62
18:15    62
10:10    62
10:45    61
14:30    61
11:45    60
15:20    59
11:30    58
09:50    58
09:10    57
20:00    57
11:50    56
18:50    55
19:00    55
10:15    55
12:30    54
18:20    54
08:40    54
18:40    54
07:50    53
17:15    53
16:45    53
15:50    52
Name: time, dtype: int64


Police Dept/ALL-LBPD-AB953.csv concatenated!

/var/folders/td/yc8lq2qx2ks3ck292tbf6wtm0000gn/T/ipykernel_9625/2746216705.py:25: DtypeWarning: Columns (2,3,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, index_col=None)

Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (68527, 7) nd PD/ALL-OAKLAND_PD-AB953.csv is starting main file
 16:30:00    203
17:00:00    198
16:00:00    196
15:30:00    183
16:15:00    181
17:15:00    179
16:45:00    177
17:30:00    173
16:55:00    171
16:20:00    169
15:00:00    168
17:05:00    167
16:25:00    167
16:40:00    165
10:00:00    165
09:30:00    163
18:00:00    160
20:00:00    155
16:50:00    152
08:30:00    151
16:35:00    151
09:50:00    150
17:50:00    148
17:10:00    146
17:20:00    145
09:00:00    145
10:30:00    144
09:20:00    139
15:20:00    138
09:40:00    138
15:50:00    138
15:40:00    136
18:30:00    132
15:45:00    131
17:25:00    130
17:40:00    129
15:35:00    129
19:30:00    124
16:10:00    122
16:44:00    122
14:20:00    120
17:45:00    118
09:15:00    117
17:35:00    116
11:00:00    116
15:55:00    116
08:50:00    115
17:07:00    115
10:20:00    114
09:45:00    114
Name: time, dtype: int64


nd PD/ALL-OAKLAND_PD-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (6466, 7) /Berkeley PD/ALL-BPD-AB953.csv is starting main file
 22:52    16
22:51    16
22:30    16
22:36    15
16:50    15
12:24    14
22:20    14
00:03    14
00:05    14
22:42    13
23:10    13
22:17    13
21:53    13
22:45    13
22:05    13
22:55    13
12:33    12
21:27    12
21:55    12
00:02    12
11:45    12
22:58    12
00:15    12
21:43    12
21:30    12
23:20    11
00:24    11
23:04    11
11:49    11
23:25    11
23:05    11
20:45    11
22:14    11
22:46    11
21:50    11
22:00    11
13:51    11
22:15    11
23:23    11
00:28    11
11:09    11
22:48    11
22:33    11
15:07    11
08:56    11
22:37    11
13:30    11
09:53    11
21:15    11
00:00    11
Name: time, dtype: int64


/Berkeley PD/ALL-BPD-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (4746, 7) ifs Office/ALL-MARIN-AB953.csv is starting main file
 21:15:00    21
22:05:00    18
22:11:00    18
22:57:00    17
21:55:00    16
21:40:00    16
22:30:00    15
21:03:00    15
22:32:00    14
20:45:00    14
22:20:00    14
21:43:00    14
20:30:00    13
00:24:00    13
22:49:00    13
23:00:00    13
21:21:00    13
21:30:00    13
22:15:00    13
22:18:00    13
21:07:00    12
21:36:00    12
00:30:00    12
21:09:00    12
23:21:00    12
22:43:00    12
21:20:00    12
21:53:00    12
00:10:00    12
22:04:00    12
22:37:00    11
22:40:00    11
22:28:00    11
22:45:00    11
22:39:00    11
13:11:00    11
20:50:00    11
11:40:00    11
22:07:00    11
23:08:00    11
20:36:00    11
00:20:00    11
20:55:00    11
23:35:00    11
21:45:00    11
22:25:00    11
22:55:00    10
00:07:00    10
22:08:00    10
21:18:00    10
Name: time, dtype: int64


ifs Office/ALL-MARIN-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (1496, 7) 4/Davis PD/ALL-DAVIS-AB953.csv is starting main file
 middle eastern or south asian    85
09:36:10                          3
02:58:29                          3
00:58:45                          3
11:05:01                          3
10:41:38                          2
10:30:31                          2
22:18:39                          2
18:32:59                          2
14:06:00                          2
13:59:17                          2
14:49:31                          2
22:43:04                          2
23:51:47                          2
20:03:13                          2
21:15:19                          2
21:11:56                          2
00:26:16                          2
00:53:26                          2
20:23:00                          2
02:48:26                          2
11:33:42                          2
02:25:55                          2
23:14:13                          2
00:03:23                          2
00:26:17                          2
23:12:24                          2
02:59:15                          2
01:41:57                          2
09:27:50                          2
12:07:07                          2
06:27:56                          2
03:07:40                          2
02:28:07                          2
17:09:33                          2
23:10:40                          2
01:23:47                          2
13:47:03                          2
21:41:39                          2
00:00:13                          2
20:08:35                          2
21:39:47                          2
22:27:24                          2
02:27:18                          2
09:21:32                          2
00:29:14                          2
01:09:06                          2
00:39:11                          2
03:20:07                          1
23:25:16                          1
Name: time, dtype: int64


4/Davis PD/ALL-DAVIS-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (314497, 7) fs Dpt/ALL-RIVERSIDE-AB953.csv is starting main file
 02:00:49    3027
11:25:46    2561
11:45:13    2404
09:03:51    1970
12:01:00    1678
02:00:00    1322
11:30:01    1303
04:25:00    1178
03:34:00    1161
12:16:18    1015
06:48:29     964
12:45:00     956
11:41:00     933
11:28:49     866
07:30:00     865
12:30:00     810
09:23:43     804
12:24:00     801
02:04:27     797
08:10:31     761
06:45:00     735
08:06:57     729
09:00:00     670
06:02:00     665
11:45:42     629
09:58:00     622
12:03:02     589
07:00:57     584
08:26:53     578
08:48:00     570
09:27:00     552
06:32:00     540
03:28:09     523
09:40:33     523
04:59:49     483
03:01:58     481
10:00:00     477
07:47:18     454
03:49:36     453
05:02:49     448
01:47:00     443
01:04:00     442
05:10:00     438
02:32:39     434
11:50:48     433
11:14:00     428
08:34:00     425
07:00:00     411
12:27:48     409
10:12:00     405
Name: time, dtype: int64


fs Dpt/ALL-RIVERSIDE-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (246655, 7) Wave 1/SDPD/ALL-SDPD-AB953.csv is starting main file
 10:00:00    497
09:00:00    479
16:00:00    456
10:30:00    448
09:30:00    448
08:30:00    448
08:00:00    427
17:00:00    390
09:50:00    385
08:50:00    376
08:40:00    373
09:45:00    373
22:00:00    370
08:45:00    366
10:15:00    360
11:00:00    357
15:00:00    357
09:15:00    353
09:20:00    352
10:20:00    347
08:15:00    342
10:10:00    337
15:30:00    330
09:10:00    330
21:00:00    326
09:40:00    326
08:55:00    318
13:00:00    317
10:40:00    312
18:00:00    305
08:20:00    303
08:10:00    295
09:25:00    294
10:50:00    292
23:00:00    292
10:35:00    291
10:25:00    290
09:35:00    289
09:55:00    287
09:05:00    286
07:50:00    286
16:30:00    285
08:35:00    283
10:45:00    281
07:45:00    279
07:30:00    272
13:30:00    266
19:00:00    265
08:05:00    265
20:00:00    264
Name: time, dtype: int64


Wave 1/SDPD/ALL-SDPD-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (1602977, 7) Wave 1/LAPD/ALL-LAPD-AB953.csv is starting main file
 09:00    6496
08:30    6297
10:00    5840
09:30    5695
08:00    5660
08:50    5240
08:40    5234
08:45    5183
16:00    5079
09:10    5043
08:20    4946
15:00    4945
09:20    4925
10:30    4893
09:15    4887
08:15    4863
17:00    4839
08:10    4768
09:40    4707
15:30    4631
09:50    4628
09:45    4584
11:00    4514
16:30    4499
08:25    4319
08:35    4314
08:55    4308
07:50    4280
14:30    4217
09:05    4191
07:30    4129
07:55    4123
07:45    4112
10:15    4104
08:05    4093
10:10    4074
09:25    4073
09:35    3990
14:00    3939
10:20    3935
17:30    3858
16:20    3827
16:45    3816
15:45    3815
18:00    3784
16:15    3777
10:40    3763
15:15    3752
07:40    3682
09:55    3671
Name: time, dtype: int64


Wave 1/LAPD/ALL-LAPD-AB953.csv concatenated!

/var/folders/td/yc8lq2qx2ks3ck292tbf6wtm0000gn/T/ipykernel_9625/2746216705.py:25: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, index_col=None)

Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (130977, 7) stem data) /ALL-SFPD-AB953.csv is starting main file
 17:00    457
16:00    387
10:00    377
16:30    363
16:40    353
16:45    338
16:50    330
18:00    323
9:00     316
17:30    312
16:20    302
16:55    298
11:30    293
16:15    293
11:00    293
12:00    282
9:30     281
14:00    279
10:30    275
16:35    275
13:00    273
8:30     271
16:25    271
17:05    264
16:10    260
17:10    258
15:00    253
22:00    252
17:40    251
17:35    245
23:00    245
17:20    245
22:30    243
8:00     242
17:15    242
17:25    239
12:30    239
16:48    237
15:40    230
17:45    225
16:38    224
9:50     224
17:04    224
11:45    223
15:45    221
10:45    221
16:44    219
18:30    218
19:00    218
10:10    216
Name: time, dtype: int64


stem data) /ALL-SFPD-AB953.csv concatenated!
Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object') (1602977, 7) stem data) /ALL-LAPD-AB953.csv is starting main file
 09:00    6496
08:30    6297
10:00    5840
09:30    5695
08:00    5660
08:50    5240
08:40    5234
08:45    5183
16:00    5079
09:10    5043
08:20    4946
15:00    4945
09:20    4925
10:30    4893
09:15    4887
08:15    4863
17:00    4839
08:10    4768
09:40    4707
15:30    4631
09:50    4628
09:45    4584
11:00    4514
16:30    4499
08:25    4319
08:35    4314
08:55    4308
07:50    4280
14:30    4217
09:05    4191
07:30    4129
07:55    4123
07:45    4112
10:15    4104
08:05    4093
10:10    4074
09:25    4073
09:35    3990
14:00    3939
10:20    3935
17:30    3858
16:20    3827
16:45    3816
15:45    3815
18:00    3784
16:15    3777
10:40    3763
15:15    3752
07:40    3682
09:55    3671
Name: time, dtype: int64


stem data) /ALL-LAPD-AB953.csv concatenated!
final shape of main is (4066431, 7)

In [972]:
main.columns

Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object')

In [973]:
main['sex'].value_counts()

Male      2942580
Female    1069721
Name: sex, dtype: int64

In [974]:
main.loc[main['type']=='middle eastern or south asian','type']=None
main.loc[main['type']=='middle eastern or south asian','type']=None
main.loc[main['duration']=='0-9','duration']=5
 

type_list=[]
main['type'] = main['type'].astype(str)

for i in main['type']:
    if '1' in i:
        type_list.append('Moving')
    elif '2' in i:
        type_list.append('Equipment')
    elif '3' in i:
        type_list.append('Non-Moving')
    
    elif 'equipment' in i.lower():
        type_list.append('Equipment')
    elif 'non' in i.lower():
        type_list.append('Non-Moving')
    else:
        type_list.append(None)
main['type'] = type_list


main.loc[main['race'] == 'Asian','race'] = 'asian'    
main.loc[main['race'] == 'Black/African American','race'] = 'black/african american'    
main.loc[main['race'] == 'black/african american','race'] = 'black/african american'    

main.loc[main['race'] == 'Hispanic/Latino','race'] = 'hispanic/latino(a)'   
main.loc[main['race'] == 'Hispanic/Latino/a','race'] = 'hispanic/latino(a)'    
main.loc[main['race'] == 'White','race'] = 'white'
main.loc[main['race'] == 'asian','race'] = 'asian'    
main.loc[main['race'] == 'black/african american','race'] = 'black/african american'    
main.loc[main['race'] == 'hispanic/latino','race'] = 'hispanic/latino(a)'    

main.loc[main['race'] == 'white','race'] = 'white'

main.loc[main['race'] == '1','race'] = 'asian'
main.loc[main['race'] == '2','race'] = 'black/african american'
main.loc[main['race'] == '3','race'] = 'hispanic/latino(a)'
main.loc[main['race'] == 'hispanic/latino/a','race'] = 'hispanic/latino(a)'
main.loc[main['race'] == '7','race'] = 'white'
main.loc[main['race'] == 1,'race'] = 'asian'
main.loc[main['race'] == 2,'race'] = 'black/african american'
main.loc[main['race'] == 3,'race'] = 'hispanic/latino(a)'
main.loc[main['race'] == 7,'race'] = 'white'

main['race'] = main['race'].astype(str)
mixed_list = []
for i in main['race']:
    if i not in ['white','asian','black/african american','hispanic/latino(a)']:
        mixed_list.append('group 4')
    else: 
        mixed_list.append(i)
main['race'] = mixed_list
      


sex_list = []
main['sex'] = main['sex'].astype(str)

main.loc[main['sex'] == 1,'sex'] = 'male'
main.loc[main['sex'] == 'Male','sex'] = 'male'
main.loc[main['sex'] == 2,'sex'] = 'female'
main.loc[main['sex'] == 'Female','sex'] = 'female'
main.loc[main['sex']==3,'sex'] = None
main.loc[main['sex']==4,'sex'] = None

def sex_code(i):
    if '1' in i:
        return 'Male'
    elif '2' in i:
        return 'Female'
    elif 'female' in i or 'Female' in i:
        return 'Female'
    elif 'male' in i or 'Male' in i:
        return 'Male'
    else: 
        return None
        
main['sex'] = [sex_code(i) if i is not None else i for i in main['sex']]
# [f(x) if x is not None else '' for x in xs]        
main['sex'].value_counts()

Male      2942580
Female    1069721
Name: sex, dtype: int64

In [975]:
main.loc[main['time']=='00-04 HRS','time']= '06:00'
main.loc[main['time']=='04-08 HRS','time']= '06:00'
main.loc[main['time']=='08-12 HRS','time']= '10:00'
main.loc[main['time']=='12-16 HRS','time']= '14:00'
main.loc[main['time']=='16-20 HRS','time']= '18:00'
main.loc[main['time']=='20-24 HRS','time']= '22:00'
main.loc[main['time']=='middle eastern or south asian','time'] = '11:45'
main.loc[main['date']=='middle eastern or south asian','date'] = '2019-04-20'

# main['time'] = main['time'].astype(str)
# main['time'] = [i[:-3] if len(i)==8 else i for i in main['time']]
# main['time'] = pd.to_datetime(main['time']) 

# main['time'] = main['time'].dt.time

In [976]:
main.loc[main['duration']=='10-19','duration']=15
main.loc[main['duration']=='20-30','duration']=25
main.loc[main['duration']=='middle eastern or south asian','duration'] = 20

main['duration'] = main.duration.replace({'minutes\xa0':'',
                                          'minutes\xa0':'',
                                          ' minutes':'',
                                          ' minutes ':'',
                                          ' Minutes ':'',
                                          ' Minutes':'',
                                          ' \xa0':'',
                                          '\xa0':'',
                                          ' min':'',
                                          'min':'',
                                          ' utes':'',
                                          '0-9':6,
                                          '10-19':15,
                                          '20-30':25,
                                          'Five':5,
                                          'Over 30':45,
                                          'One Hour':60,
                                          'One hour':60,
                                          '6/n':6},regex=True)

main['duration'] = pd.to_numeric(main['duration'])

In [977]:
for col in main.columns:
    print('\n\n',col,'\n',main[col].value_counts())

 date
 06/25/2019             5926
06/18/2019             5621
06/21/2019             5608
06/27/2019             5604
06/17/2019             5170
                       ...
2019-02-22 12:51:07       1
2019-02-22 12:52:10       1
2019-02-22 12:15:36       1
2019-02-22 12:57:32       1
2019-08-28 07:25:14       1
Name: date, Length: 207760, dtype: int64


 time
 09:00       13367
08:30       12901
10:00       12499
09:30       11705
08:00       11593
            ...
14:18:20        1
16:06:40        1
15:37:54        1
11:03:56        1
00:13:03        1
Name: time, Length: 82927, dtype: int64


 sex
 Male      2942580
Female    1069721
Name: sex, dtype: int64


 race
 hispanic/latino(a)        1818052
black/african american     951210
white                      860057
group 4                    256624
asian                      180488
Name: race, dtype: int64


 type
 Non-Moving    1072756
Equipment      577784
Name: type, dtype: int64


 duration
    10.00    841280
    5.00    519183
   15.00    369118
   20.00    230756
   30.00    150231
             ...
1,216.00         1
1,407.00         1
1,433.00         1
1,418.00         1
1,333.00         1
Name: duration, Length: 1096, dtype: int64


 city
 LAPD                    1602977
ALL-LAPD-AB953          1602977
ALL-RIVERSIDE-AB953      314497
SDPD                     246655
ALL-SFPD-AB953           130977
ALL-OAKLAND_PD-AB953      68527
ALL-SJPD-AB953            50443
ALL-LBPD-AB953            36670
Berkeley PD                6466
ALL-MARIN-AB953            4746
Davis PD                   1496
Name: city, dtype: int64

In [4]:
cd

/Users/karatechop

In [5]:
cd /Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022\ \(CSV\)

/Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022 (CSV)

In [983]:
main = main[main['city']!='LAPD']

In [984]:
main.to_csv('working_main.csv',index=False)
print('working_main saved!',main.shape)

working_main saved! (2463454, 7)

## Method #1 LOG REGRESSION

In [129]:
import pandas as pd
import numpy as np

import scipy
import statsmodels.formula.api as smf
import statistics as st 
import pandas as pd
import matplotlib.pyplot as plt
import requests
from geopy.geocoders import Nominatim
from astral import LocationInfo
import datetime
from astral.sun import sun
from astral import LocationInfo
from alive_progress import alive_bar
import time

In [130]:
cd

/Users/karatechop

In [131]:
cd /Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022\ \(CSV\)

/Users/karatechop/Documents/GitHub/senior-thesis-pretextual-stops/Data/RIPA-DATA-CA-as-of-2022 (CSV)

In [134]:
working_main = pd.read_csv('working_main.csv')
print(working_main.columns,'\n',working_main.shape,'\n',len(working_main.time))

Index(['date', 'time', 'sex', 'race', 'type', 'duration', 'city'], dtype='object')
 (2463454, 7)
 2463454

In [135]:
working_main

,date,time,sex,race,type,duration,city
0,12/09/2021,13:00,Male,hispanic/latino(a),Non-Moving,5.00,ALL-SJPD-AB953
1,04/26/21,23:00,Male,black/african american,NaN,60.00,ALL-SJPD-AB953
2,04/15/21,11:35,Female,black/african american,Equipment,10.00,ALL-SJPD-AB953
3,04/01/21,01:53,Male,asian,Non-Moving,100.00,ALL-SJPD-AB953
4,12/20/2021,16:07,Female,white,NaN,10.00,ALL-SJPD-AB953
...,...,...,...,...,...,...,...
2463449,11/02/2021,00:19,Female,hispanic/latino(a),Non-Moving,74.00,ALL-LAPD-AB953
2463450,11/02/2021,00:14,Male,hispanic/latino(a),Non-Moving,81.00,ALL-LAPD-AB953
2463451,11/01/2021,01:00,Male,hispanic/latino(a),NaN,13.00,ALL-LAPD-AB953
2463452,11/01/2021,01:00,Male,hispanic/latino(a),Non-Moving,13.00,ALL-LAPD-AB953
2463453,11/01/2021,01:00,Male,hispanic/latino(a),Non-Moving,13.00,ALL-LAPD-AB953

In [139]:
time = []
for i in range(len(working_main['time'])): 
    current = working_main.loc[i,'time']
    
    if len(working_main.loc[i,'time']) < 8:
        time.append(current + ':00')
    elif len(working_main.loc[i,'time']) > 8:
        time.append(current[11:19])
    else:
        time.append(current)
        
working_main['time'] = time
working_main['time'] = pd.to_datetime(working_main['time'],format="%H:%M:%S")
print('len of time column is:',len(working_main.time),'\n sum of null time values is:',working_main['time'].isna().sum())

len of time column is: 2463454
 sum of null time values is: 0

In [127]:
date_to_subtract = datetime.datetime(1900, 1, 1)

working_main['totalminutes_stop_time'] = [((i - date_to_subtract).total_seconds()/60) for i in working_main['time']]
working_main['totalminutes_sunsettime'] = [((i - date_to_subtract).total_seconds()/60) for i in working_main['sunsettime']]
working_main['time_to_sunset'] = working_main['totalminutes_sunsettime'] - working_main['totalminutes_stop_time']

print(working_main['time_to_sunset'].isna().sum())
working_main.head(5)

[780.0, 1380.0, 695.0, 113.0, 967.0, 960.0, 615.0, 589.0, 457.0, 444.0]

In [122]:
(working_main['time'][22] - datetime.datetime(1900, 1, 1)).total_seconds()/60

529.0

In [24]:
working_main['time'].isna().sum()

0

In [161]:
working_main = working_main.rename(columns={'city':'agency'})

def city_from_agency_check(df):
    city_str = []
    lat_str = []
    lon_str = []
    wave_str = []
    
    for i in df['agency']:
        if 'ALL-SJPD-AB953' in i:
            city_str.append('San Jose')
            lat_str.append(37.3387)
            lon_str.append(-121.8853)
            wave_str.append(2)
        elif 'ALL-LBPD-AB953' in i:
            city_str.append('Long Beach')
            lat_str.append(33.7701)
            lon_str.append(-118.1937)
            wave_str.append(2)
        elif 'ALL-OAKLAND_PD-AB953' in i:
            city_str.append('Oakland')
            lat_str.append(37.8044)
            lon_str.append(-122.2712)
            wave_str.append(2)
        elif 'Berkeley PD' in i:
            city_str.append('Berkeley')
            lat_str.append(37.8715)
            lon_str.append(-122.2730)
            wave_str.append(3)
        elif 'ALL-MARIN-AB953' in i:
            city_str.append('Marin')
            lat_str.append(38.0834)
            lon_str.append(-122.7633)
            wave_str.append(3)
        elif 'Davis PD' in i:
            city_str.append('Davis')
            lat_str.append(38.5449)
            lon_str.append(-121.7405)
            wave_str.append(3)
        elif 'ALL-RIVERSIDE-AB953' in i:
            city_str.append('Riverside')
            lat_str.append(33.9806)
            lon_str.append(-117.3755)
            wave_str.append(1)
        elif 'SDPD' in i:
            city_str.append('San Diego')
            lat_str.append(32.7157)
            lon_str.append(-117.1611)
            wave_str.append(1)
        elif 'ALL-SFPD-AB953' in i:
            city_str.append('San Francisco')
            lat_str.append(37.7749)
            lon_str.append(-122.4194)
            wave_str.append(1)
        elif 'ALL-LAPD-AB953' in i:
            city_str.append('Los Angeles')
            lat_str.append(34.0522)
            lon_str.append(-118.2437)
            wave_str.append(1)
        
    df['city']=city_str
    df['lat']=lat_str
    df['lon']=lon_str
    df['wave']=wave_str
    
    pd.option_context('display.precision', 10)
    
    return df

working_main = city_from_agency_check(working_main)
working_main

,datetime,date,time,race,sex,type,agency,city,lat,lon,wave
0,2021-12-09 00:00:00 13:00,2021-12-09 00:00:00,13:00,hispanic/latino(a),Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2
1,2021-04-26 00:00:00 23:00,2021-04-26 00:00:00,23:00,black/african american,Male,NaN,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2
2,2021-04-15 00:00:00 11:35,2021-04-15 00:00:00,11:35,black/african american,Female,Equipment,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2
3,2021-04-01 00:00:00 01:53,2021-04-01 00:00:00,01:53,asian,Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2
4,2021-12-20 00:00:00 16:07,2021-12-20 00:00:00,16:07,white,Female,NaN,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2
...,...,...,...,...,...,...,...,...,...,...,...
2463449,2021-11-02 00:00:00 00:19,2021-11-02 00:00:00,00:19,hispanic/latino(a),Female,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.0522,-118.2437,1
2463450,2021-11-02 00:00:00 00:14,2021-11-02 00:00:00,00:14,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.0522,-118.2437,1
2463451,2021-11-01 00:00:00 01:00,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,NaN,ALL-LAPD-AB953,Los Angeles,34.0522,-118.2437,1
2463452,2021-11-01 00:00:00 01:00,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.0522,-118.2437,1
2463453,2021-11-01 00:00:00 01:00,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.0522,-118.2437,1

In [162]:
# %%timeit
start = time.time()

sunset_list = []
counter = 0


for i in working_main['date']:
    year = i.year
    month = i.month
    day = i.day

    name = working_main['city'][counter]
    lat = working_main['lat'][counter]
    lon = working_main['lon'][counter]

    loc = LocationInfo(name='SF', region='CA, USA', timezone='America/Los_Angeles', #https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
                       latitude=lat, longitude=lon)
    


    s = sun(loc.observer, date=datetime.date(year, month, day), tzinfo=loc.timezone)
    for key in ['sunset']:
        sunset_list.append(s[key])
        
    counter+=1

print(f'that whole process took{(time.time()-start)/60} minutes')

KeyboardInterrupt:

In [ ]:
df = working_main
sunset_time2 = [str(i)[:-13] for i in sunset_list]
sunset_time_dt = pd.to_datetime(sunset_time2)
df['sunsettime'] = sunset_time_dt

In [ ]:
%%timeit
df['sunsettime'] = [str(i)[-8:] for i in df['sunsettime']]

In [11]:
df = pd.read_csv('working_times_VOD.csv')
# df = df.iloc[:,1:]
df
# df.to_csv('working_times_VOD.csv',index=False)

,date,time,race,sex,type,agency,city,lat,lon,wave,sunsettime
0,2021-12-09 00:00:00,13:00,hispanic/latino(a),Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,16:49
1,2021-04-26 00:00:00,23:00,black/african american,Male,NaN,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,19:52
2,2021-04-15 00:00:00,11:35,black/african american,Female,Equipment,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,19:42
3,2021-04-01 00:00:00,01:53,asian,Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,19:30
4,2021-12-20 00:00:00,16:07,white,Female,NaN,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,16:52
...,...,...,...,...,...,...,...,...,...,...,...
2463449,2021-11-02 00:00:00,00:19,hispanic/latino(a),Female,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:58
2463450,2021-11-02 00:00:00,00:14,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:58
2463451,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,NaN,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:59
2463452,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:59
2463453,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:59

In [12]:
type(df['time'])

pandas.core.series.Series

In [155]:
working_main = df
working_main['time'] = pd.to_datetime(working_main['date'],format='%H:%M')
working_main['sunsettime'] = pd.to_datetime(working_main['sunsettime'],format='%H:%M')

working_main['tosunset'] = (working_main['sunsettime'] - working_main['time'])
working_main

# tosunset = [str(i)[:-13] for i in working_main['tosunset']]
# tosunsetdt = (pd.to_datetime(tosunset,format='%H:%M')).total_seconds()/60
# working_main['tosunset'] = tosunsetdt

# working_main['time'] = working_main.time.dt.strftime('%H:%M')
# working_main['sunsettime'] = working_main.sunsettime.dt.strftime('%H:%M')

# working_main.head()

ValueError: time data '2021-12-09 00:00:00' does not match format '%H:%M' (match)

In [147]:
tosunset

['0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '-1 d',
 '0 ',
 '-1 d',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 '0 ',
 ...]

In [138]:
working_main.head()

,date,time,race,sex,type,agency,city,lat,lon,wave,sunsettime,tosunset
0,2021-12-09 00:00:00,13:00,hispanic/latino(a),Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2,16:49,0 days 03:49:00
1,2021-04-26 00:00:00,23:00,black/african american,Male,NaN,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2,19:52,-1 days +20:52:00
2,2021-04-15 00:00:00,11:35,black/african american,Female,Equipment,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2,19:42,0 days 08:07:00
3,2021-04-01 00:00:00,01:53,asian,Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2,19:30,0 days 17:37:00
4,2021-12-20 00:00:00,16:07,white,Female,NaN,ALL-SJPD-AB953,San Jose,37.3387,-121.8853,2,16:52,0 days 00:45:00

In [134]:
working_main.to_csv('working_times_VOD.csv')

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [72]:
print(working_main.shape)
# one_hot_encoded_main = pd.get_dummies(working_main, columns = ['sex','race'],drop=False,prefix='') #https://www.geeksforgeeks.org/ml-one-hot-encoding-of-datasets-in-python/
VOD = working_main[working_main['type']!='Non-Moving'][['datetime','race']]

(2463454, 11)

KeyError: "['datetime'] not in index"

In [ ]:
race_options = ['white','black','hispanic','asian','report_risk_groups','bipoc']


for race in race_options:
    formula = f"_black/african american ~ C({race}, Treatment(reference=0)) + perceivedage"
    log_reg = smf.logit(formula, data = df).fit()
    results = log_reg.summary()
    OR = pd.DataFrame(
        {
            "OR": log_reg.params,
            "Lower CI": log_reg.conf_int()[0],
            "Upper CI": log_reg.conf_int()[1],
        },
    )
    OR = np.exp(OR)
    
    print(f"\n\n{race} model (LARGE)\n{OR}\n\n\n{results}\n\n\n\n\n\n\n\n\n")

In [120]:
with_VOD = pd.read_csv('working_times_VOD.csv')

In [121]:
with_VOD

,date,time,race,sex,type,agency,city,lat,lon,wave,sunsettime
0,2021-12-09 00:00:00,13:00,hispanic/latino(a),Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,16:49
1,2021-04-26 00:00:00,23:00,black/african american,Male,NaN,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,19:52
2,2021-04-15 00:00:00,11:35,black/african american,Female,Equipment,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,19:42
3,2021-04-01 00:00:00,01:53,asian,Male,Non-Moving,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,19:30
4,2021-12-20 00:00:00,16:07,white,Female,NaN,ALL-SJPD-AB953,San Jose,37.34,-121.89,2,16:52
...,...,...,...,...,...,...,...,...,...,...,...
2463449,2021-11-02 00:00:00,00:19,hispanic/latino(a),Female,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:58
2463450,2021-11-02 00:00:00,00:14,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:58
2463451,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,NaN,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:59
2463452,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:59
2463453,2021-11-01 00:00:00,01:00,hispanic/latino(a),Male,Non-Moving,ALL-LAPD-AB953,Los Angeles,34.05,-118.24,1,17:59

## Method #2 VISUALIZATION AROUND DUSK